# Generated by Django 5.1.5 on 2025-01-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TraceabilityData",
            fields=[
                ("sr_no", models.AutoField(primary_key=True, serialize=False)),
                ("part_number", models.CharField(max_length=100, unique=True)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("shift", models.CharField(blank=True, max_length=10, null=True)),
                ("st1_result", models.CharField(blank=True, max_length=10, null=True)),
                ("st2_result", models.CharField(blank=True, max_length=10, null=True)),
                ("st3_result", models.CharField(blank=True, max_length=10, null=True)),
                ("st4_result", models.CharField(blank=True, max_length=10, null=True)),
                ("st5_result", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
